<a href="https://colab.research.google.com/github/sreshtav-0/Machine-Learning/blob/LogisticRegression/LogisticRegressionQ3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [4]:
loan = pd.read_csv("/content/loan_data.csv. - Sheet1.csv")
loan

     Age  Income  Loanamount  Creditscore Default
0     41   67133       20262          543      NO
1     43   76017       18434          537     YES
2     51   81433       15195          511      NO
3     39   72243       13302          460     YES
4     55   84449       19914          452      NO
..   ...     ...         ...          ...     ...
115   55   59345       21254          591     YES
116   39   63302       26012          417     YES
117   58   62971       22397          477     YES
118   45   80861       15206          595      NO
119   63   78113       28834          568      NO

[120 rows x 5 columns]

In [5]:
x=loan.iloc[:, :3]
y=loan.iloc[:, 4]

In [6]:
scaler=StandardScaler()

In [7]:
x

     Age  Income  Loanamount
0     41   67133       20262
1     43   76017       18434
2     51   81433       15195
3     39   72243       13302
4     55   84449       19914
..   ...     ...         ...
115   55   59345       21254
116   39   63302       26012
117   58   62971       22397
118   45   80861       15206
119   63   78113       28834

[120 rows x 3 columns]

In [8]:
y

0       NO
1      YES
2       NO
3      YES
4       NO
      ...
115    YES
116    YES
117    YES
118     NO
119     NO
Name: Default, Length: 120, dtype: object

In [9]:
xtrain, xtest, ytrain, ytest=train_test_split(x, y, train_size=0.8, random_state=0)

In [10]:
xtrain=scaler.fit_transform(xtrain)

In [11]:
xtest=scaler.transform(xtest)

In [12]:
model=LogisticRegression()

In [13]:
model.fit(xtrain, ytrain)

LogisticRegression()

In [14]:
ypred=model.predict(xtest)

In [15]:
accuracy_score(ypred, ytest)

0.6666666666666666

In [16]:
confusion_matrix(ypred, ytest)

array([[16,  7],
       [ 1,  0]])