<a href="https://colab.research.google.com/github/sreshtav-0/Machine-Learning/blob/Pandas/Pandas_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
lst=[1,2,3,4,5]
lS=pd.Series(lst)
lS

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
lS.apply(lambda x:x+2)

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [ ]:
lS.apply(lambda x:3*(x+2))

0     9
1    12
2    15
3    18
4    21
dtype: int64

In [ ]:
Country=['Japan','China','India','USA']
value=[80, 450, 200, 250]
q1S=pd.Series(data=Country, index=value)
q1S

80     Japan
450    China
200    India
250      USA
dtype: object

In [ ]:
q2={'Brazil':100,'China':200,'India':210,'USA':260}
q2S=pd.Series(q2)
q2S

Brazil    100
China     200
India     210
USA       260
dtype: int64

In [ ]:
q1S[80]

'Japan'

In [ ]:
q2S.iloc[[0, 3]]

Brazil    100
USA       260
dtype: int64

In [ ]:
q3S=q1S+q2S
q3S

80        NaN
200       NaN
250       NaN
450       NaN
Brazil    NaN
China     NaN
India     NaN
USA       NaN
dtype: object

In [ ]:
q3D=pd.DataFrame(q3S)
q3D

          0
80      NaN
200     NaN
250     NaN
450     NaN
Brazil  NaN
China   NaN
India   NaN
USA     NaN