<a href="https://colab.research.google.com/github/sreshtav-0/Machine-Learning/blob/Pandas/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Pandas is a powerful data analysis library for the processing, analysis, and manipulation of data
#3 types of data structures: Series, Dataframes, Panels
#Series-1D labeled homogenous array
#Dataframe-2D labeled homogenous tabular data structure(Series+Series=DataFrame)
#Panel is a 3D labeled array

#Start of PANDAS

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
a=[1,2,3,4,5]
s1=pd.Series(a)
print (s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
s2=pd.Series(a,index=["a","b","c","d","e"])
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
s2=pd.Series(a,index=["a","b","c","d","e"], dtype=float)
s2

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

In [ ]:
s2=pd.Series(a,index=["a","b","c","d","e"], dtype=float, name="Hello")
s2

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: Hello, dtype: float64

In [ ]:
scaler=pd.Series(0.5)
print(scaler)

0    0.5
dtype: float64

In [ ]:
scaler=pd.Series(0.5, index=[1,2,3])
print(scaler)

1    0.5
2    0.5
3    0.5
dtype: float64

In [ ]:
d={"a":1,"b":2,"c":3,"d":4,"e":5}
d

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [ ]:
d_Series=pd.Series(d)
d_Series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
d_Series[2:4]

c    3
d    4
dtype: int64

In [ ]:
max(d_Series)

5

In [ ]:
min(d_Series)

1

In [ ]:
a1=[1,2,3,4,5]
s1=pd.Series(a1)
print (s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
b1=[1,2,3,4,5]
t1=pd.Series(b1)
print (t1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
t1+s1

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
t1**s1

0       1
1       4
2      27
3     256
4    3125
dtype: int64

In [ ]:
x=[[1, "alpha", 21], [2, "beta", 25], [3, "charlie", 29]]
df=pd.DataFrame(x, columns=["ID", "name", "age"])
df

   ID     name  age
0   1    alpha   21
1   2     beta   25
2   3  charlie   29

In [ ]:
y={"ID": [1, 2, 3], "name": ["alpha", "beta", "charlie"], "age": [21, 25, 29]}
df=pd.DataFrame(y)
df

   ID     name  age
0   1    alpha   21
1   2     beta   25
2   3  charlie   29

In [ ]:
z=pd.read_csv("/content/tips1.csv")
z

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
z.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
pd.read_csv("/content/tips1.csv", nrows=10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,Sun8157
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775

In [ ]:
pd.read_csv("/content/tips1.csv", nrows=10, usecols=[2, 1])

    tip     sex
0  1.01  Female
1  1.66    Male
2  3.50    Male
3  3.31    Male
4  3.61  Female
5  4.71    Male
6  2.00    Male
7  3.12    Male
8  1.96    Male
9  3.23    Male

In [ ]:
pd.read_csv("/content/tips1.csv", nrows=10, usecols=[2, 1], skiprows=[0])

   1.01  Female
0  1.66    Male
1  3.50    Male
2  3.31    Male
3  3.61  Female
4  4.71    Male
5  2.00    Male
6  3.12    Male
7  1.96    Male
8  3.23    Male
9  1.71    Male

In [ ]:
pd.read_csv("/content/tips1.csv", index_col=["Payer Name"])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Payer Name,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...
Michael Avila,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052842,Sat2657
Monica Sanders,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565404,Sat1766
Keith Wong,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747196,Sat3880
Dennis Dixon,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,Sat17
Michelle Hardin,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698139,Thur672

In [ ]:
pd.read_csv("/content/tips1.csv", index_col=8)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Payer Name,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...
Michael Avila,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052842,Sat2657
Monica Sanders,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565404,Sat1766
Keith Wong,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747196,Sat3880
Dennis Dixon,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,Sat17
Michelle Hardin,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698139,Thur672

In [ ]:
df=pd.read_csv("/content/tips1.csv")

In [ ]:
df[["total_bill", "tip"]]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [ ]:
df['tip%']=round((df["tip"]/df["total_bill"])*100)
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip%
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,6.0
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.0
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,17.0
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,14.0
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,9.0
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,10.0
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,16.0

In [ ]:
df.reset_index()

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip%
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,6.0
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.0
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,17.0
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,14.0
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.0
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.0
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,9.0
242,242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,10.0
243,243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,16.0

In [ ]:
#Removal of columns
df=df.drop("tip%", axis=1)
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

#Accessing DataFrames

In [ ]:
x=pd.read_csv("/content/tips1.csv")
x

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
x.loc[0]

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Payment ID                     Sun2959
Name: 0, dtype: object

In [ ]:
x.loc[[0, 1]]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608

In [ ]:
x.loc[[0, 1],"Payer Name"]

0    Christy Cunningham
1        Douglas Tucker
Name: Payer Name, dtype: object

In [ ]:
x.loc[7:11]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,Sun8157
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,566287581219,Sun2546
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,Sun6686

In [ ]:
x.loc[7:11, "Payer Name"]

7         Robert Buck
8     Joseph Mcdonald
9       Jerome Abbott
10      William Riley
11       Diane Macias
Name: Payer Name, dtype: object

In [ ]:
x.loc[x['total_bill']<14, "tip"]

1      1.66
6      2.00
10     1.71
16     1.67
26     2.00
       ...
228    2.72
232    3.39
233    1.47
235    1.25
236    1.00
Name: tip, Length: 70, dtype: float64

#PANDAS ILOC: Integer Location-based indexing

In [ ]:
x.iloc[[0, 1]]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608

In [ ]:
#Dropping Rows
x.drop(["smoker", "Payment ID"], axis=1)

,total_bill,tip,sex,day,time,size,price_per_person,Payer Name,CC Number
0,16.99,1.01,Female,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,10.34,1.66,Male,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,21.01,3.50,Male,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,23.68,3.31,Male,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
4,24.59,3.61,Female,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
240,27.18,2.00,Female,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
241,22.67,2.00,Male,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
242,17.82,1.75,Male,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
243,18.78,3.00,Female,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

In [ ]:
x.loc[x['sex']=="Male"]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
...,...,...,...,...,...,...,...,...,...,...,...
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [ ]:
x[x['sex']=="Male"]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
...,...,...,...,...,...,...,...,...,...,...,...
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [ ]:
x[(x['sex']=="Male")&(x['total_bill']>30)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,Sun6686
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,Sun6165
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6011787464177340,Thur7972
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,379771118886604,Sat6240
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313
219,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,502097403252,Sat8863
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777

In [ ]:
x[(x['day']=="Sat")|(x['day']=="Sun")]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [ ]:
y=["Sun", "Sat"]
x["day"].isin(y)

0       True
1       True
2       True
3       True
4       True
       ...
239     True
240     True
241     True
242     True
243    False
Name: day, Length: 244, dtype: bool

In [ ]:
def last(num):
  return str(num)[-4:]

In [ ]:
x["last4"]=x["CC Number"].apply(last)
x

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last4
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,2842
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,5404
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,7196
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,0950
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,8139

#Dropping Rows by Index

In [ ]:
x.drop("sex", axis=1)

,total_bill,tip,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
def Affordability(num):
  if num<=10:
    return "Cheap"
  elif 10<num<15:
    return "Affordable"
  elif num>=15:
    return "Expensive"

In [ ]:
x["Affordability"]=x['total_bill'].apply(Affordability)
x

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Affordability
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,Expensive
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,Affordable
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,Expensive
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,Expensive
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,Expensive
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,Expensive
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,Expensive
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,Expensive
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,Expensive
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,Expensive

In [ ]:
x.sort_values(["total_bill","Affordability"])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Affordability
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,Cheap
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,Cheap
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,Cheap
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,30432617123103,Sun9209,Cheap
149,7.51,2.00,Male,No,Thur,Lunch,2,3.76,Daniel Robbins,4823139288341889,Thur6321,Cheap
...,...,...,...,...,...,...,...,...,...,...,...,...
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,Expensive
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,Expensive
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,Expensive
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,Expensive
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,Expensive

In [ ]:
x["total_bill"].max()

170

In [ ]:
x['total_bill'].idxmax()

170

In [ ]:
x['total_bill'].min()

3.07

In [ ]:
x['total_bill'].idxmin()

67

In [ ]:
x["Affordability"].replace(to_replace="Affordable", value="ok")

0      Expensive
1             ok
2      Expensive
3      Expensive
4      Expensive
         ...
239    Expensive
240    Expensive
241    Expensive
242    Expensive
243    Expensive
Name: Affordability, Length: 244, dtype: object

In [ ]:
x["size"].unique()

array([2, 3, 4, 1, 6, 5])

In [ ]:
x["size"].nunique()

6

In [ ]:
x["day"].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [ ]:
x["day"].nunique()

4

In [ ]:
a={"Dinner":"D", "Lunch":"L"}

{'Dinner': 'D', 'Lunch': 'L'}

In [ ]:
x['time']=x['time'].map(a)

In [ ]:
x

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Affordability
0,16.99,1.01,Female,No,Sun,D,2,8.49,Christy Cunningham,3560325168603410,Sun2959,Expensive
1,10.34,1.66,Male,No,Sun,D,3,3.45,Douglas Tucker,4478071379779230,Sun4608,Affordable
2,21.01,3.50,Male,No,Sun,D,3,7.00,Travis Walters,6011812112971322,Sun4458,Expensive
3,23.68,3.31,Male,No,Sun,D,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,Expensive
4,24.59,3.61,Female,No,Sun,D,4,6.15,Tonya Carter,4832732618637221,Sun2251,Expensive
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,D,3,9.68,Michael Avila,5296068606052842,Sat2657,Expensive
240,27.18,2.00,Female,Yes,Sat,D,2,13.59,Monica Sanders,3506806155565404,Sat1766,Expensive
241,22.67,2.00,Male,Yes,Sat,D,2,11.34,Keith Wong,6011891618747196,Sat3880,Expensive
242,17.82,1.75,Male,No,Sat,D,2,8.91,Dennis Dixon,4375220550950,Sat17,Expensive
243,18.78,3.00,Female,No,Thur,D,2,9.39,Michelle Hardin,3511451626698139,Thur672,Expensive

In [ ]:
x.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [ ]:
x.shape

(244, 12)

In [ ]:
x.drop_duplicates()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Affordability
0,16.99,1.01,Female,No,Sun,D,2,8.49,Christy Cunningham,3560325168603410,Sun2959,Expensive
1,10.34,1.66,Male,No,Sun,D,3,3.45,Douglas Tucker,4478071379779230,Sun4608,Affordable
2,21.01,3.50,Male,No,Sun,D,3,7.00,Travis Walters,6011812112971322,Sun4458,Expensive
3,23.68,3.31,Male,No,Sun,D,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,Expensive
4,24.59,3.61,Female,No,Sun,D,4,6.15,Tonya Carter,4832732618637221,Sun2251,Expensive
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,D,3,9.68,Michael Avila,5296068606052842,Sat2657,Expensive
240,27.18,2.00,Female,Yes,Sat,D,2,13.59,Monica Sanders,3506806155565404,Sat1766,Expensive
241,22.67,2.00,Male,Yes,Sat,D,2,11.34,Keith Wong,6011891618747196,Sat3880,Expensive
242,17.82,1.75,Male,No,Sat,D,2,8.91,Dennis Dixon,4375220550950,Sat17,Expensive
243,18.78,3.00,Female,No,Thur,D,2,9.39,Michelle Hardin,3511451626698139,Thur672,Expensive

In [ ]:
b={"Name":["Alpha", "Alpha", "Charlie"], "Rank":[1, 1, 3]}
df=pd.DataFrame(b)
df

      Name  Rank
0    Alpha     1
1    Alpha     1
2  Charlie     3

In [ ]:
df.drop_duplicates()

TypeError: DataFrame.nsmallest() missing 2 required positional arguments: 'n' and 'columns'

In [ ]:
x.nsmallest(10, "tip")

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Affordability
67,3.07,1.00,Female,Yes,Sat,D,1,3.07,Tiffany Brock,4359488526995267,Sat3455,Cheap
92,5.75,1.00,Female,Yes,Fri,D,2,2.88,Leah Ramirez,3508911676966392,Fri3780,Cheap
111,7.25,1.00,Female,No,Sat,D,1,7.25,Terri Jones,3559221007826887,Sat4801,Cheap
236,12.60,1.00,Male,Yes,Sat,D,2,6.30,Matthew Myers,3543676378973965,Sat5032,Affordable
0,16.99,1.01,Female,No,Sun,D,2,8.49,Christy Cunningham,3560325168603410,Sun2959,Expensive
215,12.90,1.10,Female,Yes,Sat,D,2,6.45,Jessica Owen,4726904879471,Sat6983,Affordable
237,32.83,1.17,Male,Yes,Sat,D,2,16.42,Thomas Brown,4284722681265508,Sat2929,Expensive
75,10.51,1.25,Male,No,Sat,D,2,5.26,Kenneth Hayes,213142079731108,Sat5056,Affordable
135,8.51,1.25,Female,No,Thur,L,2,4.26,Rebecca Harris,4320272020376174,Thur6600,Cheap
235,10.07,1.25,Male,No,Sat,D,2,5.04,Sean Gonzalez,3534021246117605,Sat4615,Affordable

#Handling of Missing Values

In [ ]:
ms=pd.read_csv("/content/movie_scores.csv")
ms

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [ ]:
ms.isnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [ ]:
ms[ms["first_name"].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.isnull().sum()

first_name          1
last_name           1
age                 1
sex                 1
pre_movie_score     2
post_movie_score    2
dtype: int64

In [ ]:
ms.isnull().sum().sum()

8

In [ ]:
ms[(ms["pre_movie_score"].isnull()) &(ms["sex"].notnull())]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

In [ ]:
ms.dropna(axis=0)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
#Optional, default 'any'.
#Specifies whether to remove the row or column when ALL values are NULL, or if ANY value is NULL.

In [ ]:
ms.dropna(how="any")

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.dropna(how="all")

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.dropna(how="any", axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
ms.dropna(how="all", axis=1)

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
#look for atleast not null values...
#If thresh =1 then there should be atleast one not null value otherwise it drops
ms.dropna(thresh=1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.dropna(thresh=5)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.dropna(subset='pre_movie_score')

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.dropna(inplace=True)
ms

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.fillna({'pre_movie_score':0,'post_movie_score':1})

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              0.0               1.0
2       Hugh   Jackman  51.0    m              0.0               1.0
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.fillna(method="ffill")

<ipython-input-20-890e7ae87ef7>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ms.fillna(method="ffill")

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.fillna(method="pad")

<ipython-input-21-e0d60225d4e6>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ms.fillna(method="pad")

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
#ffill and pad are same method/operation/function

In [ ]:
ms.fillna(method="bfill")

<ipython-input-22-2ad6354da2f2>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ms.fillna(method="bfill")

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1       Hugh   Jackman  51.0   m              6.0               8.0
2       Hugh   Jackman  51.0   m              6.0               8.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.fillna(method="ffill", axis=1)

<ipython-input-23-8e9ffff451ee>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ms.fillna(method="ffill", axis=1)
<ipython-input-23-8e9ffff451ee>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ms.fillna(method="ffill", axis=1)

  first_name last_name   age  sex pre_movie_score post_movie_score
0        Tom     Hanks  63.0    m             8.0             10.0
1        NaN       NaN   NaN  NaN             NaN              NaN
2       Hugh   Jackman  51.0    m               m                m
3      Oprah   Winfrey  66.0    f             6.0              8.0
4       Emma     Stone  31.0    f             7.0              9.0

In [ ]:
ms.fillna(method="ffill", axis=0, limit=1)

<ipython-input-24-9c2af8bc4cba>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ms.fillna(method="ffill", axis=0, limit=1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.replace(to_replace="Emma", value="Ethan")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4      Ethan     Stone  31.0    f              7.0               9.0

In [ ]:
ms.interpolate()

<ipython-input-27-ced24b9e8424>:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  ms.interpolate()

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m         8.000000         10.000000
1        NaN       NaN  57.0  NaN         7.333333          9.333333
2       Hugh   Jackman  51.0    m         6.666667          8.666667
3      Oprah   Winfrey  66.0    f         6.000000          8.000000
4       Emma     Stone  31.0    f         7.000000          9.000000

In [ ]:
ms.interpolate(method="polynomial", order=2)

<ipython-input-32-ea57f86ac06a>:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  ms.interpolate(method="polynomial", order=2)

  first_name last_name        age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.000000    m         8.000000         10.000000
1        NaN       NaN  46.631579  NaN         6.500000          8.500000
2       Hugh   Jackman  51.000000    m         5.833333          7.833333
3      Oprah   Winfrey  66.000000    f         6.000000          8.000000
4       Emma     Stone  31.000000    f         7.000000          9.000000

In [ ]:
ms.interpolate(method="nearest")

<ipython-input-33-aff14ab5b50b>:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  ms.interpolate(method="nearest")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN  63.0  NaN              8.0              10.0
2       Hugh   Jackman  51.0    m              6.0               8.0
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.interpolate(limit=1, limit_direction="backward")

<ipython-input-34-9a6c05ce350d>:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  ms.interpolate(limit=1, limit_direction="backward")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m         8.000000         10.000000
1        NaN       NaN  57.0  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m         6.666667          8.666667
3      Oprah   Winfrey  66.0    f         6.000000          8.000000
4       Emma     Stone  31.0    f         7.000000          9.000000

#GroupBy

In [ ]:
df=x
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
g1=df.groupby(by='tip')
g1.groups

{1.0: [67, 92, 111, 236], 1.01: [0], 1.1: [215], 1.17: [237], 1.25: [75, 135, 235], 1.32: [43], 1.36: [146], 1.44: [195, 218], 1.45: [30], 1.47: [233], 1.48: [126], 1.5: [57, 97, 99, 117, 130, 132, 145, 190, 217], 1.56: [53], 1.57: [12], 1.58: [224], 1.61: [168], 1.63: [147], 1.64: [105], 1.66: [1], 1.67: [16], 1.68: [121], 1.71: [10], 1.73: [148], 1.75: [242], 1.76: [58], 1.8: [118], 1.83: [82], 1.92: [222], 1.96: [8], 1.97: [70], 1.98: [62], 2.0: [6, 26, 27, 36, 61, 86, 123, 127, 128, 133, 136, 137, 138, 149, 151, 153, 154, 159, 162, 163, 169, 176, 177, 187, 196, 198, 199, 202, 210, 226, 230, 240, 241], 2.01: [68, 201], 2.02: [193], 2.03: [84, 208], 2.05: [48], 2.09: [69], 2.18: [129], 2.2: [74, 220], 2.23: [22, 209], 2.24: [40, 166], 2.3: [144], 2.31: [38, 120], 2.34: [25], 2.45: [33], 2.47: [66], 2.5: [31, 50, 100, 102, 122, 150, 161, 203, 213, 225], 2.52: [124], 2.54: [41], 2.55: [113], 2.56: [192], 2.6: [51], 2.61: [158], 2.64: [64], 2.71: [79], 2.72: [228], 2.74: [152], 2.75: [21, 139], 2.83: [131], 2.88: [229], 2.92: [119], 3.0: [13, 29, 32, 45, 49, 56, 71, 78, 80, 89, 90, 98, 101, 110, 164, 184, 207, 216, 223, 227, 231, 234, 243], 3.02: [14], 3.06: [42], 3.07: [37], 3.08: [76], 3.09: [219], 3.11: [175], 3.12: [7], 3.14: [72], 3.15: [65], 3.16: [171], 3.18: [24, 173], 3.21: [60], 3.23: [9, 205], 3.25: [94, 134], 3.27: [34], 3.31: [3], 3.35: [19], 3.39: [232], 3.4: [81], 3.41: [206], 3.48: [103, 165, 221], 3.5: [2, 18, 91, 115, 140, 160, 182, 186, 188], 3.51: [55], 3.55: [179], 3.6: [35], 3.61: [4], 3.68: [180], 3.71: [17], 3.75: [157], 3.76: [63, 108], 3.92: [15], 4.0: [77, 87, 96, 109, 112, 114, 174, 178, 189, 194, 200, 204], 4.06: [106], 4.08: [20, 104], 4.19: [191], 4.2: [125], 4.29: [107], 4.3: [28, 93], ...}

In [ ]:
g1=df.groupby(by=['tip', 'total_bill'])
g1.groups

{(1.0, 3.07): [67], (1.0, 5.75): [92], (1.0, 7.25): [111], (1.0, 12.6): [236], (1.01, 16.99): [0], (1.1, 12.9): [215], (1.17, 32.83): [237], (1.25, 8.51): [135], (1.25, 10.07): [235], (1.25, 10.51): [75], (1.32, 9.68): [43], (1.36, 18.64): [146], (1.44, 7.56): [195], (1.44, 7.74): [218], (1.45, 9.55): [30], (1.47, 10.77): [233], (1.48, 8.52): [126], (1.5, 8.35): [145], (1.5, 10.65): [117], (1.5, 11.17): [132], (1.5, 11.59): [217], (1.5, 12.03): [97], (1.5, 12.46): [99], (1.5, 15.69): [190], (1.5, 19.08): [130], (1.5, 26.41): [57], (1.56, 9.94): [53], (1.57, 15.42): [12], (1.58, 13.42): [224], (1.61, 10.59): [168], (1.63, 11.87): [147], (1.64, 15.36): [105], (1.66, 10.34): [1], (1.67, 10.33): [16], (1.68, 13.42): [121], (1.71, 10.27): [10], (1.73, 9.78): [148], (1.75, 17.82): [242], (1.76, 11.24): [58], (1.8, 12.43): [118], (1.83, 10.07): [82], (1.92, 8.58): [222], (1.96, 15.04): [8], (1.97, 12.02): [70], (1.98, 11.02): [62], (2.0, 7.51): [149], (2.0, 8.77): [6], (2.0, 10.09): [226], (2.0, 10.33): [136], (2.0, 10.34): [196], (2.0, 10.63): [169], (2.0, 11.38): [128], (2.0, 12.26): [133], (2.0, 12.69): [27], (2.0, 13.0): [198, 202], (2.0, 13.03): [86], (2.0, 13.13): [151], (2.0, 13.37): [26], (2.0, 13.51): [199], (2.0, 13.81): [61, 163], (2.0, 14.15): [137], (2.0, 14.48): [177], (2.0, 14.52): [127], (2.0, 15.95): [123], (2.0, 16.0): [138], (2.0, 16.21): [162], (2.0, 16.31): [36], (2.0, 16.49): [159], (2.0, 17.89): [176], (2.0, 19.77): [154], (2.0, 22.67): [241], (2.0, 24.01): [230], (2.0, 24.55): [153], (2.0, 27.18): [240], (2.0, 30.06): [210], (2.0, 30.46): [187], (2.01, 12.74): [201], (2.01, 20.23): [68], (2.02, 15.48): [193], (2.03, 15.98): [84], (2.03, 24.27): [208], (2.05, 28.55): [48], (2.09, 15.01): [69], (2.18, 22.82): [129], (2.2, 12.16): [220], (2.2, 14.73): [74], (2.23, 12.76): [209], (2.23, 15.77): [22], (2.24, 16.04): [40], (2.24, 20.76): [166], (2.3, 16.43): [144], (2.31, 11.69): [120], (2.31, 18.69): [38], (2.34, 17.81): [25], (2.45, 20.69): [33], (2.47, 16.45): [66], (2.5, 11.35): [100], (2.5, 12.54): [50], (2.5, 12.66): [161], (2.5, 13.27): [213], ...}

In [ ]:
g2=df.groupby("tip").get_group(1.5)
g2

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
57,26.41,1.5,Female,No,Sat,Dinner,2,13.20,Melody Simon,4745394421258160,Sat8980
97,12.03,1.5,Male,Yes,Fri,Dinner,2,6.02,Eric Herrera,580116092652,Fri9268
99,12.46,1.5,Male,No,Fri,Dinner,2,6.23,Edward Carter,347435564751626,Fri5575
117,10.65,1.5,Female,No,Thur,Lunch,2,5.32,Linda Zhang,3560509622598239,Thur9593
130,19.08,1.5,Male,No,Thur,Lunch,2,9.54,Seth Sexton,213113680829581,Thur1446
132,11.17,1.5,Female,No,Thur,Lunch,2,5.58,Taylor Gonzalez,6011990685390011,Thur7783
145,8.35,1.5,Female,No,Thur,Lunch,2,4.18,Amy Young,4285454264477,Thur9331
190,15.69,1.5,Male,Yes,Sun,Dinner,2,7.84,Riley Barnes,180053549128800,Sun5104
217,11.59,1.5,Male,Yes,Sat,Dinner,2,5.80,Gary Orr,30324521283406,Sat8489

In [ ]:
#Merge function:
#It connects columns or indexes in the DataFrame based on one or more keys
Df1=pd.DataFrame({"ID":[1, 2, 3, 4], "Class":[5, 6, 7, 8]})
Df1

   ID  Class
0   1      5
1   2      6
2   3      7
3   4      8

In [ ]:
Df2=pd.DataFrame({"ID":[1, 2, 3, 4], "Name":["A", "B", "C", "D"]})
Df2

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D

In [ ]:
pd.merge(Df2, Df1, on="ID")

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [ ]:
pd.merge(Df1, Df1, on="ID")

   ID  Class_x  Class_y
0   1        5        5
1   2        6        6
2   3        7        7
3   4        8        8

In [ ]:
pd.merge(Df1, Df1, on="ID", suffixes=("one", "two"))

   ID  Classone  Classtwo
0   1         5         5
1   2         6         6
2   3         7         7
3   4         8         8

In [ ]:
Df3=pd.DataFrame({"ID":[1, 2, 3], "Name":["A", "B", "C"]})
Df3

   ID Name
0   1    A
1   2    B
2   3    C

In [ ]:
pd.merge(Df3, Df1, on="ID", how="left")

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7

In [ ]:
pd.merge(Df3, Df1, on="ID", how="right")

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4  NaN      8

In [ ]:
ser1=pd.Series([1, 2, 3, 4, 5])
ser2=pd.Series([6, 7, 8, 9, 0])

In [ ]:
pd.concat([ser1, ser2], ignore_index=True)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9    0
dtype: int64

In [ ]:
df=pd.DataFrame({"ID":[0, 1, 2, 3], "name":["Alpha", "Beta", "Charlie", "Delta"]})
df

   ID     name
0   0    Alpha
1   1     Beta
2   2  Charlie
3   3    Delta

In [ ]:
df1=pd.DataFrame({"ID":[4, 5, 6, 7], "name":["Echo", "Foxtrot", "Golf", "Hotel"]})
df1

   ID     name
0   4     Echo
1   5  Foxtrot
2   6     Golf
3   7    Hotel

In [ ]:
pd.concat([df, df1], axis=1)

   ID     name  ID     name
0   0    Alpha   4     Echo
1   1     Beta   5  Foxtrot
2   2  Charlie   6     Golf
3   3    Delta   7    Hotel

In [ ]:
df2=pd.DataFrame({"ID": [0, 1], "name": ["Alpha", "Beta"]})
df2

   ID   name
0   0  Alpha
1   1   Beta

In [ ]:
pd.concat([df1, df2], axis=1, join="inner")

   ID     name  ID   name
0   4     Echo   0  Alpha
1   5  Foxtrot   1   Beta

In [ ]:
pd.concat([df1, df2], axis=1, join="outer")

   ID     name   ID   name
0   4     Echo  0.0  Alpha
1   5  Foxtrot  1.0   Beta
2   6     Golf  NaN    NaN
3   7    Hotel  NaN    NaN

In [ ]:
pd.concat([df1, df2], keys=["df1", "df2"])

       ID     name
df1 0   4     Echo
    1   5  Foxtrot
    2   6     Golf
    3   7    Hotel
df2 0   0    Alpha
    1   1     Beta

In [ ]:
pd.concat([df1, df2], keys=["df1", "df2"], axis=1)

  df1           df2
   ID     name   ID   name
0   4     Echo  0.0  Alpha
1   5  Foxtrot  1.0   Beta
2   6     Golf  NaN    NaN
3   7    Hotel  NaN    NaN

In [ ]:
dfN=pd.DataFrame({"A":[1, 2, 3], "B":[10, 20, 30]}, index=["a", "b", "c"])
dfN

   A   B
a  1  10
b  2  20
c  3  30

In [ ]:
dfN2=pd.DataFrame({"C":[1, 2, 3], "D":[10, 20, 30]}, index=["a", "b", "c"])
dfN2

   C   D
a  1  10
b  2  20
c  3  30

In [ ]:
dfN.join(dfN2)

   A   B  C   D
a  1  10  1  10
b  2  20  2  20
c  3  30  3  30

In [ ]:
dfN3=pd.DataFrame({"C":[1, 2], "D":[10, 20]}, index=["a", "b"])
dfN3

   C   D
a  1  10
b  2  20

In [ ]:
dfN.join(dfN3)

   A   B    C     D
a  1  10  1.0  10.0
b  2  20  2.0  20.0
c  3  30  NaN   NaN

In [ ]:
dfN.join(dfN3, how="right")

   A   B  C   D
a  1  10  1  10
b  2  20  2  20

In [ ]:
dfN.join(dfN3, how="left")

   A   B    C     D
a  1  10  1.0  10.0
b  2  20  2.0  20.0
c  3  30  NaN   NaN

In [ ]:
dfN2.join(dfN3, how="left", lsuffix="_1")

   C_1  D_1    C     D
a    1   10  1.0  10.0
b    2   20  2.0  20.0
c    3   30  NaN   NaN

In [ ]:
dfN=pd.DataFrame({"A":[1, 2, 3], "B":[10, 20, 30]})
dfN

   A   B
0  1  10
1  2  20
2  3  30

In [ ]:
dfN2=pd.DataFrame({"C":[1, 2, 3], "D":[10, 20, 30]})
dfN2

   C   D
0  1  10
1  2  20
2  3  30